### ISSUE TITLE
configure_logging require shadowing

### ISSUE THREAD

**Issue by tcpj** [seznam/shelter#1]
When ```configure_logging``` is not shadowed in config class and logging formatters in settings.py are not defined, KeyError "formatters" is raised.

```
Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    main()
  File "/usr/lib/python3/dist-packages/shelter/main.py", line 136, in main
    command()
  File "/usr/lib/python3/dist-packages/shelter/core/commands.py", line 98, in __call__
    self.context.config.configure_logging()
  File "/usr/lib/python3/dist-packages/shelter/contrib/config/iniconfig.py", line 118, in configure_logging
    self.config_parser, disable_existing_loggers=False)
  File "/usr/lib/python3.4/logging/config.py", line 76, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/lib/python3.4/logging/config.py", line 109, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/usr/lib/python3.4/configparser.py", line 937, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'

```

Workaround:
```python
def configure_logging(self):
    pass
```

**Comment by tcpj** [comment]
Found it. Missing fallback value, when [formatters] section is not defined in ini config
```python
    def configure_logging(self):
        """
        Configure Python's logging according to configuration placed in
        configuration file.
        """
        logging.config.fileConfig(
            self.config_parser, disable_existing_loggers=False)
```

**Comment by seifert** [comment]
I'm working on version 2.0, Is it still relevant? See Python's logging documentation https://docs.python.org/3.6/library/logging.config.html#configuration-file-format and `fileConfig`, Shelter uses this function if INI config is used. Some sections are required - `[loggers]`, `[handlers]` and `[formatters]`. So it's not possible to skip this section. However, you can put empty `[formatters]` into your config:
```
[formatters]
keys=
```
